#ifndef PANDA_H
#define PANDA_H

#include "..\headers\global.h"
#include "..\headers\itempid.h"
#include "..\headers\scripts.h"
#include "..\headers\teams.h"
#include "..\headers\Condtion.h"
//#include "..\headers\RepPoint.h"
#include "..\headers\AIPacket.h"
#include "..\headers\ExpPoint.h"
#include "..\headers\ScenePid.h"
#include "..\headers\Maps.h"
#include "..\headers\animcomd.h"
#include "..\headers\CritrPid.h"
#include "..\headers\ArtFid.h"
#include "..\headers\Party.h"
#include "..\headers\Reaction.h"


#define PCSTAT_hunger		        (6)
#define PCSTAT_thirst				(7)
#define PCSTAT_stress				(8)

#define PCSSTAT_31					(31)
#define PCSSTAT_32					(32)


#endif //PANDA_H